/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { AresReward } from "./AresReward";
export type { AresStake } from "./AresStake";
export type { IReward } from "./IReward";
export type { IStake } from "./IStake";
export type { Token } from "./Token";

export { Ownable__factory } from "./factories/Ownable__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { AresReward__factory } from "./factories/AresReward__factory";
export { AresStake__factory } from "./factories/AresStake__factory";
export { IReward__factory } from "./factories/IReward__factory";
export { IStake__factory } from "./factories/IStake__factory";
export { Token__factory } from "./factories/Token__factory";
